"""
Alembic environment script.

DevOps-owned scaffold: wires alembic to read DATABASE_URL from app settings
(env var, same value docker-compose injects into the api container) so
`alembic revision` / `alembic upgrade head` work mechanically as soon as
Backend Architect adds models.

Backend Architect: once app/db/base.py (SQLAlchemy declarative Base) and
app/models/* exist, import your models' metadata below and set
`target_metadata = Base.metadata` so `alembic revision --autogenerate` works.
Until then this scaffold supports hand-written revisions.
"""
import os
import sys
from logging.config import fileConfig

from alembic import context
from sqlalchemy import engine_from_config, pool

# Make the `app` package importable when alembic is invoked from apps/api/.
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from app.core.config import settings  # noqa: E402

# this is the Alembic Config object, which provides access to the values
# within the .ini file in use.
config = context.config

# Interpret the config file for Python logging.
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# Override sqlalchemy.url from application settings (env var DATABASE_URL)
# rather than hardcoding it in alembic.ini.
config.set_main_option("sqlalchemy.url", settings.DATABASE_URL)

# app.db.base imports every model module, so Base.metadata is fully populated
# here and `alembic revision --autogenerate` sees the whole schema.
from app.db.base import Base  # noqa: E402

target_metadata = Base.metadata


#: Schemas owned by the postgis / postgis_topology / postgis_tiger_geocoder
#: extensions. The tiger geocoder puts its schemas on the search_path, so
#: autogenerate reflects hundreds of its tables and proposes dropping them.
_EXTENSION_SCHEMAS = {"tiger", "tiger_data", "topology"}

#: Extension-owned tables and views that land in the public schema.
_EXTENSION_TABLES = {
    "spatial_ref_sys",
    "geography_columns",
    "geometry_columns",
    "raster_columns",
    "raster_overviews",
}


def include_object(obj, name, type_, reflected, compare_to):
    """
    Keep PostGIS extension objects out of our migrations.

    Without this, the first autogenerated revision tries to drop the entire
    tiger geocoder schema - which would break the extension and, on downgrade,
    be unrecoverable. We only ever migrate tables this application declares.
    """
    schema = getattr(obj, "schema", None)
    if schema in _EXTENSION_SCHEMAS:
        return False
    if type_ == "table" and name in _EXTENSION_TABLES:
        return False
    return True


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode (emits SQL, no live DB connection)."""
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        include_object=include_object,
        compare_type=True,
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode against a live DB connection."""
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
        # postgis_tiger_geocoder puts `tiger` and `tiger_data` on the
        # search_path, which makes Alembic reflect several hundred of the
        # extension's tables as if they were ours and propose dropping them.
        # Pin the search_path at connection level via libpq options.
        #
        # This MUST be a connection option rather than a `SET search_path`
        # statement issued on the connection: executing any statement before
        # context.configure() opens an implicit SQLAlchemy 2.x transaction,
        # which leaves Alembic's own transaction nested and silently discards
        # the whole migration on close. That failure mode reports a successful
        # "Running upgrade" and then commits nothing.
        connect_args={"options": "-csearch_path=public"},
    )

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            include_object=include_object,
            compare_type=True,
        )

        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
