"""
Admin CMS API (PRD sections 28/29, decision D-02, contract section 8).

Every route in this module is gated by `require_admin` at the router level, so
a new endpoint added here is authenticated and role-checked by construction
rather than by the author remembering to add a dependency.

Content CRUD for the four editable types is generated by
`register_content_crud` rather than written out four times. That is not just
brevity: it guarantees that Event, Announcement, Temple and Ghat all get the
same guarded status transition, the same soft-delete semantics and the same
audit trail, so none of them can quietly drift into a free-form status write.
"""
# NOTE: deliberately no `from __future__ import annotations` in this module.
# The CRUD factory below annotates handler parameters with closure variables
# (`payload: create_schema`). PEP 563 would turn those into strings that
# FastAPI resolves against module globals, where they do not exist.
from datetime import datetime, timezone
from enum import Enum
from typing import Any

from fastapi import APIRouter, Depends, HTTPException, Query, Response, status
from sqlalchemy import func, select
from sqlalchemy.exc import IntegrityError
from sqlalchemy.orm import Session

from app.api.v1.helpers import (
    LimitQuery,
    OffsetQuery,
    apply_updates,
    count_of,
    live_rows,
)
from app.core.deps import AdminUser, DbSession, require_admin
from app.models.accommodation import Accommodation, EssentialService
from app.models.cases import LostFoundCase, MissingPersonCase
from app.models.content import Announcement, Event, Ghat, Temple
from app.models.emergency import SosIncident
from app.models.enums import ContentStatus, DataSource, RoleName
from app.models.parking import ParkingFacility
from app.models.user import User
from app.schemas.accommodation import (
    AccommodationCreate,
    AccommodationOut,
    AccommodationUpdate,
    EssentialServiceCreate,
    EssentialServiceOut,
    EssentialServiceUpdate,
)
from app.schemas.cases import (
    CaseStatusUpdate,
    LostFoundAdminOut,
    MissingPersonAdminOut,
)
from app.schemas.common import ListEnvelope, build_envelope
from app.schemas.content import (
    AnnouncementCreate,
    AnnouncementOut,
    AnnouncementUpdate,
    EventCreate,
    EventOut,
    EventUpdate,
    GhatCreate,
    GhatOut,
    GhatUpdate,
    TempleCreate,
    TempleOut,
    TempleUpdate,
)
from app.schemas.parking import ParkingCreate, ParkingOut, ParkingUpdate
from app.services.audit import record_audit
from app.services.workflow import (
    CONTENT_TRANSITIONS,
    LOST_FOUND_TRANSITIONS,
    MISSING_PERSON_TRANSITIONS,
    apply_transition,
)

router = APIRouter(
    prefix="/admin",
    tags=["admin"],
    dependencies=[Depends(require_admin)],
    responses={
        401: {"description": "Missing, malformed or expired bearer token."},
        403: {"description": "Authenticated, but this role has no admin access."},
    },
)


def _orm_payload(payload: Any) -> dict[str, Any]:
    """
    Flatten a validated schema into ORM-assignable values.

    `model_dump()` preserves Enum members, and assigning one to a VARCHAR
    column persists the repr ("EventCategory.SNAN_PARVA") rather than the
    contract value ("snan_parva"). Unwrap them once, here.
    """
    return {
        key: (value.value if isinstance(value, Enum) else value)
        for key, value in payload.model_dump().items()
    }


def _get_or_404(db: Session, model: type, item_id: int) -> Any:
    row = db.execute(
        live_rows(model).where(model.id == item_id)
    ).scalar_one_or_none()
    if row is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"{model.__name__} not found",
        )
    return row


def _commit_or_conflict(db: Session, entity_type: str) -> None:
    """Translate a unique-slug collision into 409 instead of a 500."""
    try:
        db.commit()
    except IntegrityError as exc:
        db.rollback()
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail=(
                f"Could not save {entity_type}: a record with that slug already "
                "exists."
            ),
        ) from exc


def register_content_crud(
    *,
    path: str,
    model: type,
    entity_type: str,
    out_schema: type,
    create_schema: type,
    update_schema: type,
) -> None:
    """Attach list/create/patch/delete routes for one CMS content type."""

    @router.get(
        path,
        response_model=ListEnvelope[out_schema],
        name=f"admin_list_{entity_type}",
        operation_id=f"admin_list_{entity_type}",
        summary=f"List {entity_type} records including drafts",
    )
    def _list(
        db: DbSession,
        status_filter: ContentStatus | None = Query(
            default=None, alias="status", description="Filter by publication status."
        ),
        limit: int = LimitQuery,
        offset: int = OffsetQuery,
    ) -> Any:
        stmt = live_rows(model)
        if status_filter is not None:
            stmt = stmt.where(model.status == status_filter.value)
        total = count_of(db, stmt)
        rows = (
            db.execute(stmt.order_by(model.id.asc()).limit(limit).offset(offset))
            .scalars()
            .all()
        )
        return ListEnvelope[out_schema].model_validate(
            build_envelope(rows, [out_schema.model_validate(r) for r in rows], total)
        )

    @router.post(
        path,
        response_model=out_schema,
        status_code=status.HTTP_201_CREATED,
        name=f"admin_create_{entity_type}",
        operation_id=f"admin_create_{entity_type}",
        summary=f"Create a {entity_type} record (always starts as a draft)",
        description=(
            "New records are created with `status = \"draft\"`. Publication is a "
            "separate, explicitly guarded transition via PATCH - nothing "
            "reaches the public API on creation."
        ),
    )
    def _create(payload: create_schema, db: DbSession, admin: AdminUser) -> Any:
        row = model(
            **_orm_payload(payload),
            # Not client-controlled: an editor cannot create pre-published
            # content, and cannot claim their hand-typed row is authority-sourced.
            status=ContentStatus.DRAFT.value,
            data_source=DataSource.CMS.value,
        )
        db.add(row)
        db.flush()
        record_audit(
            db,
            action=f"{entity_type}.created",
            entity_type=entity_type,
            entity_id=row.id,
            actor_user_id=admin.id,
            detail={"slug": getattr(row, "slug", None), "status": row.status},
        )
        _commit_or_conflict(db, entity_type)
        db.refresh(row)
        return out_schema.model_validate(row)

    @router.patch(
        path + "/{item_id}",
        response_model=out_schema,
        name=f"admin_update_{entity_type}",
        operation_id=f"admin_update_{entity_type}",
        summary=f"Partially update a {entity_type} record",
        description=(
            "Supports the draft/published/archived transition. Allowed moves: "
            "draft->published, published->draft, published->archived, "
            "draft->archived. Any other move is rejected with **409**; status "
            "is never written as a free-form value."
        ),
        responses={
            404: {"description": "No such record."},
            409: {"description": "Invalid status transition, or duplicate slug."},
        },
    )
    def _update(
        item_id: int, payload: update_schema, db: DbSession, admin: AdminUser
    ) -> Any:
        row = _get_or_404(db, model, item_id)
        data = {
            key: (value.value if isinstance(value, Enum) else value)
            for key, value in payload.model_dump(exclude_unset=True).items()
        }

        requested_status = data.pop("status", None)
        transitioned_to: str | None = None
        if requested_status is not None:
            new_status = apply_transition(
                CONTENT_TRANSITIONS,
                entity_type,
                row.status,
                ContentStatus(requested_status).value,
            )
            if new_status != row.status:
                transitioned_to = new_status
                row.status = new_status
                # First publication stamps published_at so the public feed can
                # order by it; re-publishing later keeps the original stamp.
                if (
                    new_status == ContentStatus.PUBLISHED.value
                    and hasattr(row, "published_at")
                    and row.published_at is None
                ):
                    row.published_at = datetime.now(timezone.utc)

        if "verified" in data and admin.role_name != RoleName.SUPER_ADMIN.value:
            # `verified` asserts that a named authority signed the record off.
            # A content manager must not be able to grant that badge.
            raise HTTPException(
                status_code=status.HTTP_403_FORBIDDEN,
                detail="Only a super_admin may change the `verified` flag.",
            )

        changed = apply_updates(row, data)
        if changed or transitioned_to:
            row.data_source = DataSource.CMS.value

        db.flush()
        record_audit(
            db,
            action=(
                f"{entity_type}.status_changed"
                if transitioned_to
                else f"{entity_type}.updated"
            ),
            entity_type=entity_type,
            entity_id=row.id,
            actor_user_id=admin.id,
            detail={
                "changed_fields": sorted(changed),
                "status_from": None if not transitioned_to else requested_status,
                "status_to": transitioned_to,
                "status": row.status,
            },
        )
        _commit_or_conflict(db, entity_type)
        db.refresh(row)
        return out_schema.model_validate(row)

    @router.delete(
        path + "/{item_id}",
        status_code=status.HTTP_204_NO_CONTENT,
        name=f"admin_delete_{entity_type}",
        operation_id=f"admin_delete_{entity_type}",
        summary=f"Retire a {entity_type} record",
        description=(
            "Soft delete. The row is marked deleted and disappears from every "
            "public and admin read, but is retained so the audit trail still "
            "resolves the record it refers to."
        ),
        responses={404: {"description": "No such record."}},
    )
    def _delete(item_id: int, db: DbSession, admin: AdminUser) -> Response:
        row = _get_or_404(db, model, item_id)
        row.deleted_at = datetime.now(timezone.utc)
        db.flush()
        record_audit(
            db,
            action=f"{entity_type}.deleted",
            entity_type=entity_type,
            entity_id=row.id,
            actor_user_id=admin.id,
            detail={"slug": getattr(row, "slug", None), "soft_delete": True},
        )
        db.commit()
        return Response(status_code=status.HTTP_204_NO_CONTENT)


register_content_crud(
    path="/events",
    model=Event,
    entity_type="event",
    out_schema=EventOut,
    create_schema=EventCreate,
    update_schema=EventUpdate,
)
register_content_crud(
    path="/announcements",
    model=Announcement,
    entity_type="announcement",
    out_schema=AnnouncementOut,
    create_schema=AnnouncementCreate,
    update_schema=AnnouncementUpdate,
)
register_content_crud(
    path="/temples",
    model=Temple,
    entity_type="temple",
    out_schema=TempleOut,
    create_schema=TempleCreate,
    update_schema=TempleUpdate,
)
register_content_crud(
    path="/ghats",
    model=Ghat,
    entity_type="ghat",
    out_schema=GhatOut,
    create_schema=GhatCreate,
    update_schema=GhatUpdate,
)
register_content_crud(
    path="/parking",
    model=ParkingFacility,
    entity_type="parking_facility",
    out_schema=ParkingOut,
    create_schema=ParkingCreate,
    update_schema=ParkingUpdate,
)
register_content_crud(
    path="/accommodation",
    model=Accommodation,
    entity_type="accommodation",
    out_schema=AccommodationOut,
    create_schema=AccommodationCreate,
    update_schema=AccommodationUpdate,
)
register_content_crud(
    path="/essential-services",
    model=EssentialService,
    entity_type="essential_service",
    out_schema=EssentialServiceOut,
    create_schema=EssentialServiceCreate,
    update_schema=EssentialServiceUpdate,
)


# --------------------------------------------------------------------------
# Verification queues
#
# This is the legitimate-purpose side of decision D-01: an authenticated
# reviewer CAN see full case detail, because verifying a missing-person report
# is impossible otherwise. The public API cannot. Every read here is a
# deliberate, authenticated, audited act.
# --------------------------------------------------------------------------
@router.get(
    "/lost-found",
    response_model=ListEnvelope[LostFoundAdminOut],
    summary="Lost & Found verification queue (full case detail)",
)
def list_lost_found_queue(
    db: DbSession,
    case_status: str | None = Query(default=None, alias="status"),
    limit: int = LimitQuery,
    offset: int = OffsetQuery,
) -> Any:
    stmt = select(LostFoundCase)
    if case_status is not None:
        stmt = stmt.where(LostFoundCase.status == case_status)
    total = count_of(db, stmt)
    rows = (
        db.execute(
            stmt.order_by(LostFoundCase.created_at.desc()).limit(limit).offset(offset)
        )
        .scalars()
        .all()
    )
    return ListEnvelope[LostFoundAdminOut].model_validate(
        build_envelope(rows, [LostFoundAdminOut.model_validate(r) for r in rows], total)
    )


@router.patch(
    "/lost-found/{item_id}",
    response_model=LostFoundAdminOut,
    summary="Move a Lost & Found case through the verification workflow",
    description=(
        "Status transition and reviewer notes only - an admin cannot rewrite "
        "what the reporter submitted. Invalid transitions are rejected with 409."
    ),
    responses={409: {"description": "Invalid status transition."}},
)
def update_lost_found_case(
    item_id: int, payload: CaseStatusUpdate, db: DbSession, admin: AdminUser
) -> Any:
    case = db.execute(
        select(LostFoundCase).where(LostFoundCase.id == item_id)
    ).scalar_one_or_none()
    if case is None:
        raise HTTPException(status_code=404, detail="Case not found")

    previous = case.status
    case.status = apply_transition(
        LOST_FOUND_TRANSITIONS, "lost_found_case", previous, payload.status
    )
    if payload.admin_notes is not None:
        case.admin_notes = payload.admin_notes
    db.flush()
    record_audit(
        db,
        action="lost_found.status_changed",
        entity_type="lost_found_case",
        entity_id=case.id,
        actor_user_id=admin.id,
        detail={
            "case_reference": case.case_reference,
            "status_from": previous,
            "status_to": case.status,
        },
    )
    db.commit()
    db.refresh(case)
    return LostFoundAdminOut.model_validate(case)


@router.get(
    "/missing-person",
    response_model=ListEnvelope[MissingPersonAdminOut],
    summary="Missing-person verification queue (full case detail)",
    description=(
        "Authenticated reviewers only. This is the sole route that returns "
        "missing-person personal detail; the public status endpoint returns "
        "status and timestamps only."
    ),
)
def list_missing_person_queue(
    db: DbSession,
    admin: AdminUser,
    case_status: str | None = Query(default=None, alias="status"),
    limit: int = LimitQuery,
    offset: int = OffsetQuery,
) -> Any:
    stmt = select(MissingPersonCase)
    if case_status is not None:
        stmt = stmt.where(MissingPersonCase.status == case_status)
    total = count_of(db, stmt)
    rows = (
        db.execute(
            stmt.order_by(MissingPersonCase.created_at.desc())
            .limit(limit)
            .offset(offset)
        )
        .scalars()
        .all()
    )
    # Reading a queue of children's personal details is itself a sensitive act,
    # so the read is audited, not just the writes (PRD section 30).
    record_audit(
        db,
        action="missing_person.queue_viewed",
        entity_type="missing_person_case",
        entity_id=None,
        actor_user_id=admin.id,
        detail={"returned": len(rows), "status_filter": case_status},
    )
    db.commit()
    return ListEnvelope[MissingPersonAdminOut].model_validate(
        build_envelope(
            rows, [MissingPersonAdminOut.model_validate(r) for r in rows], total
        )
    )


@router.patch(
    "/missing-person/{item_id}",
    response_model=MissingPersonAdminOut,
    summary="Move a missing-person case through the verification workflow",
    description=(
        "Status transition and reviewer notes only. Invalid transitions are "
        "rejected with 409. Note that `resolved` and `closed` are terminal: "
        "reopening a missing-person case is a decision for police, not a CMS "
        "dropdown."
    ),
    responses={409: {"description": "Invalid status transition."}},
)
def update_missing_person_case(
    item_id: int, payload: CaseStatusUpdate, db: DbSession, admin: AdminUser
) -> Any:
    case = db.execute(
        select(MissingPersonCase).where(MissingPersonCase.id == item_id)
    ).scalar_one_or_none()
    if case is None:
        raise HTTPException(status_code=404, detail="Case not found")

    previous = case.status
    case.status = apply_transition(
        MISSING_PERSON_TRANSITIONS, "missing_person_case", previous, payload.status
    )
    if payload.admin_notes is not None:
        case.admin_notes = payload.admin_notes
    db.flush()
    record_audit(
        db,
        action="missing_person.status_changed",
        entity_type="missing_person_case",
        entity_id=case.id,
        actor_user_id=admin.id,
        detail={
            "case_reference": case.case_reference,
            "status_from": previous,
            "status_to": case.status,
        },
    )
    db.commit()
    db.refresh(case)
    return MissingPersonAdminOut.model_validate(case)


# --------------------------------------------------------------------------
# Dashboard
# --------------------------------------------------------------------------
def _counts_by_status(db: Session, model: type, soft_deleted: bool = True) -> dict[str, int]:
    stmt = select(model.status, func.count()).group_by(model.status)
    if soft_deleted and hasattr(model, "deleted_at"):
        stmt = stmt.where(model.deleted_at.is_(None))
    return {row[0]: int(row[1]) for row in db.execute(stmt).all()}


@router.get(
    "/dashboard",
    summary="Admin dashboard counts by entity and status",
    description=(
        "Aggregate counts only - no personal data. The SOS block reports the "
        "count of SIMULATED incident records held in this prototype's own "
        "database; it is not a count of real dispatches, because there are none."
    ),
)
def dashboard(db: DbSession) -> dict[str, Any]:
    content = {
        "events": _counts_by_status(db, Event),
        "announcements": _counts_by_status(db, Announcement),
        "temples": _counts_by_status(db, Temple),
        "ghats": _counts_by_status(db, Ghat),
    }
    cases = {
        "lost_found": _counts_by_status(db, LostFoundCase, soft_deleted=False),
        "missing_person": _counts_by_status(db, MissingPersonCase, soft_deleted=False),
    }
    sos_total = int(
        db.execute(select(func.count()).select_from(SosIncident)).scalar_one()
    )
    users_total = int(
        db.execute(
            select(func.count()).select_from(User).where(User.deleted_at.is_(None))
        ).scalar_one()
    )

    def _totalled(block: dict[str, dict[str, int]]) -> dict[str, dict[str, Any]]:
        return {
            key: {"total": sum(counts.values()), "by_status": counts}
            for key, counts in block.items()
        }

    return {
        "generated_at": datetime.now(timezone.utc)
        .replace(microsecond=0)
        .isoformat()
        .replace("+00:00", "Z"),
        "content": _totalled(content),
        "cases": _totalled(cases),
        "sos": {"total": sos_total, "simulated": sos_total},
        "users": {"total": users_total},
        "prototype_notice": (
            "Counts reflect this prototype's own test database only. No figure "
            "here represents a real incident, dispatch or authority-verified record."
        ),
    }
