"""sprint1 core schema

Revision ID: 9d5271c283a9
Revises: 
Create Date: 2026-09-20 08:00:13.793658+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9d5271c283a9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # PostGIS must exist before any geometry column is created. The
    # postgis/postgis image already installs it, but stating it here keeps the
    # migration self-sufficient against a plain postgres instance.
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")

    # NOTE: the GiST indexes on the geometry columns (idx_<table>_geom,
    # idx_zones_boundary) are intentionally absent from this file. GeoAlchemy2
    # registers them against the Table and emits them as part of CREATE TABLE,
    # so repeating them here raises DuplicateTable. They are likewise dropped
    # implicitly with their tables on downgrade.

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=32), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('data_source', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_announcements_created_at'), 'announcements', ['created_at'], unique=False)
    op.create_index(op.f('ix_announcements_priority'), 'announcements', ['priority'], unique=False)
    op.create_index(op.f('ix_announcements_published_at'), 'announcements', ['published_at'], unique=False)
    op.create_index(op.f('ix_announcements_status'), 'announcements', ['status'], unique=False)
    op.create_index('uq_announcements_slug_active', 'announcements', ['slug'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('venue_name', sa.String(length=255), nullable=True),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('data_source', sa.String(length=32), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_category'), 'events', ['category'], unique=False)
    op.create_index(op.f('ix_events_created_at'), 'events', ['created_at'], unique=False)
    op.create_index('ix_events_starts_at_status', 'events', ['starts_at', 'status'], unique=False)
    op.create_index(op.f('ix_events_status'), 'events', ['status'], unique=False)
    op.create_index('uq_events_slug_active', 'events', ['slug'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('lost_found_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_reference', sa.String(length=32), nullable=False),
    sa.Column('report_type', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location_text', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('reporter_name', sa.String(length=255), nullable=True),
    sa.Column('reporter_phone', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lost_found_cases_case_reference'), 'lost_found_cases', ['case_reference'], unique=True)
    op.create_index(op.f('ix_lost_found_cases_created_at'), 'lost_found_cases', ['created_at'], unique=False)
    op.create_index(op.f('ix_lost_found_cases_status'), 'lost_found_cases', ['status'], unique=False)
    op.create_table('missing_person_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_reference', sa.String(length=32), nullable=False),
    sa.Column('person_name', sa.String(length=255), nullable=False),
    sa.Column('person_age', sa.Integer(), nullable=True),
    sa.Column('person_gender', sa.String(length=32), nullable=True),
    sa.Column('physical_description', sa.Text(), nullable=True),
    sa.Column('last_seen_location_text', sa.Text(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('photo_url', sa.String(length=512), nullable=True),
    sa.Column('reporter_name', sa.String(length=255), nullable=True),
    sa.Column('reporter_phone', sa.String(length=64), nullable=False),
    sa.Column('reporter_relationship', sa.String(length=64), nullable=True),
    sa.Column('consent_given', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_missing_person_cases_case_reference'), 'missing_person_cases', ['case_reference'], unique=True)
    op.create_index(op.f('ix_missing_person_cases_created_at'), 'missing_person_cases', ['created_at'], unique=False)
    op.create_index(op.f('ix_missing_person_cases_status'), 'missing_person_cases', ['status'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_created_at'), 'roles', ['created_at'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('sos_incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_reference', sa.String(length=32), nullable=False),
    sa.Column('situation_category', sa.String(length=64), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('reporter_name', sa.String(length=255), nullable=True),
    sa.Column('reporter_phone', sa.String(length=64), nullable=True),
    sa.Column('consent_given', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('simulated', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sos_incidents_case_reference'), 'sos_incidents', ['case_reference'], unique=True)
    op.create_index(op.f('ix_sos_incidents_created_at'), 'sos_incidents', ['created_at'], unique=False)
    op.create_table('zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('zone_type', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('boundary', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zones_created_at'), 'zones', ['created_at'], unique=False)
    op.create_index('uq_zones_slug_active', 'zones', ['slug'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('emergency_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('hours', sa.String(length=128), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('data_source', sa.String(length=32), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_emergency_services_category', 'emergency_services', ['category', 'status'], unique=False)
    op.create_index(op.f('ix_emergency_services_created_at'), 'emergency_services', ['created_at'], unique=False)
    op.create_index(op.f('ix_emergency_services_status'), 'emergency_services', ['status'], unique=False)
    op.create_index(op.f('ix_emergency_services_zone_id'), 'emergency_services', ['zone_id'], unique=False)
    op.create_table('ghats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('bathing_info', sa.Text(), nullable=True),
    sa.Column('facilities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('accessibility_info', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('operational_status', sa.String(length=32), nullable=False),
    sa.Column('advisory', sa.Text(), nullable=True),
    sa.Column('crowd_level', sa.String(length=32), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('data_source', sa.String(length=32), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ghats_created_at'), 'ghats', ['created_at'], unique=False)
    op.create_index(op.f('ix_ghats_status'), 'ghats', ['status'], unique=False)
    op.create_index(op.f('ix_ghats_zone_id'), 'ghats', ['zone_id'], unique=False)
    op.create_index('uq_ghats_slug_active', 'ghats', ['slug'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('temples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('significance', sa.Text(), nullable=True),
    sa.Column('timings', sa.Text(), nullable=True),
    sa.Column('aarti_schedule', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('transport_info', sa.Text(), nullable=True),
    sa.Column('accessibility_info', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('data_source', sa.String(length=32), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_temples_created_at'), 'temples', ['created_at'], unique=False)
    op.create_index(op.f('ix_temples_status'), 'temples', ['status'], unique=False)
    op.create_index(op.f('ix_temples_zone_id'), 'temples', ['zone_id'], unique=False)
    op.create_index('uq_temples_slug_active', 'temples', ['slug'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index('uq_temples_slug_active', table_name='temples', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_temples_zone_id'), table_name='temples')
    op.drop_index(op.f('ix_temples_status'), table_name='temples')
    op.drop_index(op.f('ix_temples_created_at'), table_name='temples')
    op.drop_table('temples')
    op.drop_index('uq_ghats_slug_active', table_name='ghats', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_ghats_zone_id'), table_name='ghats')
    op.drop_index(op.f('ix_ghats_status'), table_name='ghats')
    op.drop_index(op.f('ix_ghats_created_at'), table_name='ghats')
    op.drop_table('ghats')
    op.drop_index(op.f('ix_emergency_services_zone_id'), table_name='emergency_services')
    op.drop_index(op.f('ix_emergency_services_status'), table_name='emergency_services')
    op.drop_index(op.f('ix_emergency_services_created_at'), table_name='emergency_services')
    op.drop_index('ix_emergency_services_category', table_name='emergency_services')
    op.drop_table('emergency_services')
    op.drop_index('uq_zones_slug_active', table_name='zones', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_zones_created_at'), table_name='zones')
    op.drop_table('zones')
    op.drop_index(op.f('ix_sos_incidents_created_at'), table_name='sos_incidents')
    op.drop_index(op.f('ix_sos_incidents_case_reference'), table_name='sos_incidents')
    op.drop_table('sos_incidents')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_created_at'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_missing_person_cases_status'), table_name='missing_person_cases')
    op.drop_index(op.f('ix_missing_person_cases_created_at'), table_name='missing_person_cases')
    op.drop_index(op.f('ix_missing_person_cases_case_reference'), table_name='missing_person_cases')
    op.drop_table('missing_person_cases')
    op.drop_index(op.f('ix_lost_found_cases_status'), table_name='lost_found_cases')
    op.drop_index(op.f('ix_lost_found_cases_created_at'), table_name='lost_found_cases')
    op.drop_index(op.f('ix_lost_found_cases_case_reference'), table_name='lost_found_cases')
    op.drop_table('lost_found_cases')
    op.drop_index('uq_events_slug_active', table_name='events', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_events_status'), table_name='events')
    op.drop_index('ix_events_starts_at_status', table_name='events')
    op.drop_index(op.f('ix_events_created_at'), table_name='events')
    op.drop_index(op.f('ix_events_category'), table_name='events')
    op.drop_table('events')
    op.drop_index('uq_announcements_slug_active', table_name='announcements', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_announcements_status'), table_name='announcements')
    op.drop_index(op.f('ix_announcements_published_at'), table_name='announcements')
    op.drop_index(op.f('ix_announcements_priority'), table_name='announcements')
    op.drop_index(op.f('ix_announcements_created_at'), table_name='announcements')
    op.drop_table('announcements')
    # ### end Alembic commands ###

    # The postgis extension is deliberately NOT dropped on downgrade: other
    # schemas in the same database may depend on it, and re-creating it needs
    # privileges a downgrade should not assume.
