"""phase 2-3 batch: parking, accommodation, crowd, incidents

Revision ID: 5a1afcf9d337
Revises: 9d5271c283a9
Create Date: 2026-09-20 11:01:30.981296+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '5a1afcf9d337'
down_revision: Union[str, None] = '9d5271c283a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # NOTE: the GiST indexes on the geometry columns (idx_accommodations_geom,
    # idx_essential_services_geom, idx_parking_facilities_geom) are
    # intentionally absent from this file. GeoAlchemy2 registers them against
    # the Table and emits them as part of CREATE TABLE, so repeating them here
    # raises DuplicateTable. They are likewise dropped implicitly with their
    # tables on downgrade.

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accommodations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('accommodation_type', sa.String(length=32), nullable=False),
    sa.Column('price_tier', sa.String(length=32), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('data_source', sa.String(length=32), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accommodations_created_at'), 'accommodations', ['created_at'], unique=False)
    op.create_index(op.f('ix_accommodations_status'), 'accommodations', ['status'], unique=False)
    op.create_index('ix_accommodations_type_status', 'accommodations', ['accommodation_type', 'status'], unique=False)
    op.create_index(op.f('ix_accommodations_zone_id'), 'accommodations', ['zone_id'], unique=False)
    op.create_index('uq_accommodations_slug_active', 'accommodations', ['slug'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('essential_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('data_source', sa.String(length=32), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_essential_services_category_status', 'essential_services', ['category', 'status'], unique=False)
    op.create_index(op.f('ix_essential_services_created_at'), 'essential_services', ['created_at'], unique=False)
    op.create_index(op.f('ix_essential_services_status'), 'essential_services', ['status'], unique=False)
    op.create_index(op.f('ix_essential_services_zone_id'), 'essential_services', ['zone_id'], unique=False)
    op.create_index('uq_essential_services_slug_active', 'essential_services', ['slug'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('parking_facilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parking_type', sa.String(length=32), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('current_occupancy', sa.Integer(), nullable=True),
    sa.Column('occupancy_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('entry_info', sa.Text(), nullable=True),
    sa.Column('exit_info', sa.Text(), nullable=True),
    sa.Column('shuttle_note', sa.Text(), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('data_source', sa.String(length=32), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parking_facilities_created_at'), 'parking_facilities', ['created_at'], unique=False)
    op.create_index(op.f('ix_parking_facilities_status'), 'parking_facilities', ['status'], unique=False)
    op.create_index('ix_parking_facilities_type_status', 'parking_facilities', ['parking_type', 'status'], unique=False)
    op.create_index(op.f('ix_parking_facilities_zone_id'), 'parking_facilities', ['zone_id'], unique=False)
    op.create_index('uq_parking_facilities_slug_active', 'parking_facilities', ['slug'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('crowd_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('density_level', sa.String(length=32), nullable=False),
    sa.Column('estimated_count_band', sa.String(length=32), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('recorded_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crowd_readings_created_at'), 'crowd_readings', ['created_at'], unique=False)
    op.create_index(op.f('ix_crowd_readings_recorded_at'), 'crowd_readings', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_crowd_readings_zone_id'), 'crowd_readings', ['zone_id'], unique=False)
    op.create_index('ix_crowd_readings_zone_recorded', 'crowd_readings', ['zone_id', 'recorded_at'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('escalated', sa.Boolean(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('assigned_department', sa.String(length=128), nullable=True),
    sa.Column('sla_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reported_by_user_id', sa.Integer(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('simulated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reported_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_category'), 'incidents', ['category'], unique=False)
    op.create_index(op.f('ix_incidents_created_at'), 'incidents', ['created_at'], unique=False)
    op.create_index(op.f('ix_incidents_priority'), 'incidents', ['priority'], unique=False)
    op.create_index(op.f('ix_incidents_reported_by_user_id'), 'incidents', ['reported_by_user_id'], unique=False)
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    op.create_index('ix_incidents_status_priority', 'incidents', ['status', 'priority'], unique=False)
    op.create_index(op.f('ix_incidents_zone_id'), 'incidents', ['zone_id'], unique=False)
    op.add_column('lost_found_cases', sa.Column('matched_case_id', sa.Integer(), nullable=True))
    op.create_foreign_key('lost_found_cases_matched_case_id_fkey', 'lost_found_cases', 'lost_found_cases', ['matched_case_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('lost_found_cases_matched_case_id_fkey', 'lost_found_cases', type_='foreignkey')
    op.drop_column('lost_found_cases', 'matched_case_id')
    op.drop_index(op.f('ix_incidents_zone_id'), table_name='incidents')
    op.drop_index('ix_incidents_status_priority', table_name='incidents')
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_reported_by_user_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_priority'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_created_at'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_category'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index('ix_crowd_readings_zone_recorded', table_name='crowd_readings')
    op.drop_index(op.f('ix_crowd_readings_zone_id'), table_name='crowd_readings')
    op.drop_index(op.f('ix_crowd_readings_recorded_at'), table_name='crowd_readings')
    op.drop_index(op.f('ix_crowd_readings_created_at'), table_name='crowd_readings')
    op.drop_table('crowd_readings')
    op.drop_index('uq_parking_facilities_slug_active', table_name='parking_facilities', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_parking_facilities_zone_id'), table_name='parking_facilities')
    op.drop_index('ix_parking_facilities_type_status', table_name='parking_facilities')
    op.drop_index(op.f('ix_parking_facilities_status'), table_name='parking_facilities')
    op.drop_index(op.f('ix_parking_facilities_created_at'), table_name='parking_facilities')
    op.drop_table('parking_facilities')
    op.drop_index('uq_essential_services_slug_active', table_name='essential_services', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_essential_services_zone_id'), table_name='essential_services')
    op.drop_index(op.f('ix_essential_services_status'), table_name='essential_services')
    op.drop_index(op.f('ix_essential_services_created_at'), table_name='essential_services')
    op.drop_index('ix_essential_services_category_status', table_name='essential_services')
    op.drop_table('essential_services')
    op.drop_index('uq_accommodations_slug_active', table_name='accommodations', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_accommodations_zone_id'), table_name='accommodations')
    op.drop_index('ix_accommodations_type_status', table_name='accommodations')
    op.drop_index(op.f('ix_accommodations_status'), table_name='accommodations')
    op.drop_index(op.f('ix_accommodations_created_at'), table_name='accommodations')
    op.drop_table('accommodations')
    # ### end Alembic commands ###
